import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { getRun, getTransactions, exportRunUrl } from "@/lib/api";
import { formatINR, formatDate, formatDateTime } from "@/lib/format";
import { DownloadSimple, ArrowLeft } from "@phosphor-icons/react";
import { toast } from "sonner";
import ReportTable from "@/pages/ReportTable";
import ReconTable from "@/pages/ReconTable";

const BUCKET_LABEL = {
  col2: "Total expenditure (all buckets)",
  col3: "Col 3 · Exempt supply (registered party)",
  col4: "Col 4 · Composition dealer",
  col5: "Col 5 · Other Registered (ITC voucher)",
  col6: "Col 6 · Aggregate registered (3+4+5)",
  col7: "Col 7 · Unregistered",
};

export default function StepReport() {
  const { runId } = useParams();
  const navigate = useNavigate();
  const [run, setRun] = useState(null);
  const [loading, setLoading] = useState(true);
  const [drill, setDrill] = useState(null);

  useEffect(() => {
    (async () => {
      try {
        const r = await getRun(runId);
        if (!r.generated) {
          navigate(`/dashboard/runs/${runId}`);
          return;
        }
        setRun(r);
      } catch (e) {
        toast.error("Failed to load run");
      } finally {
        setLoading(false);
      }
    })();
  }, [runId, navigate]);

  const openDrill = async (bucket, ledger) => {
    setDrill({ bucket, ledger, txns: null, loading: true });
    try {
      const data = await getTransactions(runId, bucket === "col2" ? "all" : bucket, ledger || undefined);
      setDrill({ bucket, ledger, txns: data.transactions, loading: false });
    } catch {
      toast.error("Failed to load transactions");
      setDrill(null);
    }
  };

  const ledgerRows = useMemo(() => {
    if (!run?.by_ledger) return [];
    return Object.entries(run.by_ledger).map(([name, v]) => ({
      name,
      col3: v.col3 || 0, col4: v.col4 || 0, col5: v.col5 || 0, col7: v.col7 || 0,
      col6: (v.col3 || 0) + (v.col4 || 0) + (v.col5 || 0),
      col2_total: v.total != null ? v.total : (v.col3 || 0) + (v.col4 || 0) + (v.col5 || 0) + (v.col7 || 0),
    })).sort((a, b) => b.col2_total - a.col2_total);
  }, [run]);

  if (loading || !run) return <div className="p-10 font-mono text-sm text-[#8A8A83]">Loading…</div>;
  const periodTag = run.period ? `FY ${run.period}` : "";
  const divisionTag = run.division_name ? `· ${run.division_name}` : "";

  return (
    <div className="px-6 md:px-10 py-8 pb-40 max-w-[1400px]" data-testid="report-page">
      <div className="flex items-start justify-between gap-6 flex-wrap">
        <div>
          <div className="font-mono text-[11px] uppercase tracking-[0.15em] text-[#8A8A83]">
            {run.client_name} · {periodTag} {divisionTag}
          </div>
          <h2 className="mt-1 font-heading text-2xl tracking-tight">{run.company_name || "Clause 44"}</h2>
          {run.generated_by_name && (
            <div className="mt-2 inline-flex items-center gap-2 font-mono text-[11px] text-[#52524E] bg-emerald-50 border border-emerald-200 rounded-sm px-2 py-1" data-testid="generated-by-chip">
              <span className="w-1.5 h-1.5 bg-emerald-600 rounded-full"></span>
              <span>Generated by <strong className="text-emerald-900">{run.generated_by_name}</strong> · {formatDateTime(run.generated_at)}</span>
            </div>
          )}
          <p className="mt-3 text-sm text-[#52524E]">
            Click any cell to open the underlying transactions. Switch to the Reconciliation tab to tie books to the schedule.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            onClick={() => navigate(`/dashboard/runs/${runId}`)}
            className="h-10 px-4 border-[#D4D4D0] rounded-sm shadow-none gap-2"
            data-testid="back-to-mapping-btn"
          >
            <ArrowLeft size={14}/> Edit Mapping
          </Button>
          <Button
            asChild
            className="h-10 px-4 bg-[#0F172A] hover:bg-[#1E293B] text-white rounded-sm shadow-none gap-2"
            data-testid="export-excel-btn"
          >
            <a href={exportRunUrl(runId)} download>
              <DownloadSimple size={14} weight="bold"/>Download Detailed Breakup
            </a>
          </Button>
        </div>
      </div>

      <div className="mt-8">
        <Tabs defaultValue="report" className="w-full">
          <TabsList className="bg-[#F3F4F1] border border-[#E5E5E0] rounded-sm p-1 h-auto">
            <TabsTrigger value="report" className="font-mono text-[11px] uppercase tracking-[0.12em] data-[state=active]:bg-white" data-testid="tab-report">Schedule</TabsTrigger>
            <TabsTrigger value="recon" className="font-mono text-[11px] uppercase tracking-[0.12em] data-[state=active]:bg-white" data-testid="tab-recon">Reconciliation</TabsTrigger>
          </TabsList>
          <TabsContent value="report" className="mt-6">
            <ReportTable summary={run.summary} ledgerRows={ledgerRows} openDrill={openDrill}/>
          </TabsContent>
          <TabsContent value="recon" className="mt-6">
            <ReconTable recon={run.recon}/>
          </TabsContent>
        </Tabs>
      </div>

      <Sheet open={!!drill} onOpenChange={(o) => !o && setDrill(null)}>
        <SheetContent side="right" className="w-full sm:max-w-2xl lg:max-w-3xl p-0 bg-white" data-testid="drilldown-sheet">
          <SheetHeader className="px-6 pt-6 pb-4 border-b border-[#E5E5E0]">
            <SheetTitle className="font-heading text-xl tracking-tight">{drill?.ledger ? `${drill.ledger}` : "Aggregate"}</SheetTitle>
            <SheetDescription className="text-[12px] text-[#52524E]">{BUCKET_LABEL[drill?.bucket] || ""}</SheetDescription>
            {drill?.txns && (
              <div className="flex items-center gap-3 mt-2 font-mono text-[11px] text-[#52524E]">
                <Badge className="bg-slate-100 text-slate-800 rounded-sm shadow-none border-slate-200">{drill.txns.length} txns</Badge>
                <span>·</span>
                <span>Σ {formatINR(drill.txns.reduce((a, t) => a + t.amount, 0))}</span>
              </div>
            )}
          </SheetHeader>
          <div className="overflow-y-auto h-[calc(100vh-110px)]">
            {drill?.loading && <div className="p-8 font-mono text-sm text-[#8A8A83]">Loading transactions…</div>}
            {drill?.txns && drill.txns.length === 0 && <div className="p-8 text-sm text-[#8A8A83]">No transactions in this bucket.</div>}
            {drill?.txns && drill.txns.length > 0 && (
              <table className="fiscal-table w-full" data-testid="drilldown-table">
                <thead><tr><th>Date</th><th>Voucher</th><th>Ledger</th><th>Party</th><th className="text-right">Amount</th><th>Reason</th></tr></thead>
                <tbody>
                  {drill.txns.map((t, i) => (
                    <tr key={`${t.voucher_id}_${i}`}>
                      <td className="num text-[12px]">{formatDate(t.date)}</td>
                      <td className="num text-[12px]">{t.voucher_type}<br/><span className="text-[#8A8A83]">{t.voucher_number}</span></td>
                      <td className="text-[12px] max-w-[160px] truncate">{t.ledger_name}</td>
                      <td className="text-[12px] max-w-[180px]">{t.party_name || <em className="text-[#8A8A83]">—</em>}{t.party_gstin && <div className="font-mono text-[10px] text-[#8A8A83]">{t.party_gstin}</div>}</td>
                      <td className="cell-num text-[12px]">{formatINR(t.amount)}</td>
                      <td className="text-[11px] text-[#52524E] max-w-[260px]">{t.reason}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </SheetContent>
      </Sheet>
    </div>
  );
}
